/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/app/': RouteRecordInfo<'/app/', '/app', Record<never, never>, Record<never, never>>,
    '/app/budgets': RouteRecordInfo<'/app/budgets', '/app/budgets', Record<never, never>, Record<never, never>>,
    '/app/categories': RouteRecordInfo<'/app/categories', '/app/categories', Record<never, never>, Record<never, never>>,
    '/app/expenses': RouteRecordInfo<'/app/expenses', '/app/expenses', Record<never, never>, Record<never, never>>,
    '/app/incomes': RouteRecordInfo<'/app/incomes', '/app/incomes', Record<never, never>, Record<never, never>>,
    '/app/profile': RouteRecordInfo<'/app/profile', '/app/profile', Record<never, never>, Record<never, never>>,
    '/app/transfers': RouteRecordInfo<'/app/transfers', '/app/transfers', Record<never, never>, Record<never, never>>,
    '/app/wallets': RouteRecordInfo<'/app/wallets', '/app/wallets', Record<never, never>, Record<never, never>>,
    '/auth/callback': RouteRecordInfo<'/auth/callback', '/auth/callback', Record<never, never>, Record<never, never>>,
    '/auth/reset-password': RouteRecordInfo<'/auth/reset-password', '/auth/reset-password', Record<never, never>, Record<never, never>>,
    '/forgot-password': RouteRecordInfo<'/forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/mobile/': RouteRecordInfo<'/mobile/', '/mobile', Record<never, never>, Record<never, never>>,
    '/mobile/budgets': RouteRecordInfo<'/mobile/budgets', '/mobile/budgets', Record<never, never>, Record<never, never>>,
    '/mobile/categories': RouteRecordInfo<'/mobile/categories', '/mobile/categories', Record<never, never>, Record<never, never>>,
    '/mobile/manage': RouteRecordInfo<'/mobile/manage', '/mobile/manage', Record<never, never>, Record<never, never>>,
    '/mobile/profile': RouteRecordInfo<'/mobile/profile', '/mobile/profile', Record<never, never>, Record<never, never>>,
    '/mobile/reports': RouteRecordInfo<'/mobile/reports', '/mobile/reports', Record<never, never>, Record<never, never>>,
    '/mobile/wallets': RouteRecordInfo<'/mobile/wallets', '/mobile/wallets', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...all].vue': {
      routes: '/[...all]'
      views: never
    }
    'src/pages/app/index.vue': {
      routes: '/app/'
      views: never
    }
    'src/pages/app/budgets.vue': {
      routes: '/app/budgets'
      views: never
    }
    'src/pages/app/categories.vue': {
      routes: '/app/categories'
      views: never
    }
    'src/pages/app/expenses.vue': {
      routes: '/app/expenses'
      views: never
    }
    'src/pages/app/incomes.vue': {
      routes: '/app/incomes'
      views: never
    }
    'src/pages/app/profile.vue': {
      routes: '/app/profile'
      views: never
    }
    'src/pages/app/transfers.vue': {
      routes: '/app/transfers'
      views: never
    }
    'src/pages/app/wallets.vue': {
      routes: '/app/wallets'
      views: never
    }
    'src/pages/auth/callback.vue': {
      routes: '/auth/callback'
      views: never
    }
    'src/pages/auth/reset-password.vue': {
      routes: '/auth/reset-password'
      views: never
    }
    'src/pages/forgot-password.vue': {
      routes: '/forgot-password'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/mobile/index.vue': {
      routes: '/mobile/'
      views: never
    }
    'src/pages/mobile/budgets.vue': {
      routes: '/mobile/budgets'
      views: never
    }
    'src/pages/mobile/categories.vue': {
      routes: '/mobile/categories'
      views: never
    }
    'src/pages/mobile/manage.vue': {
      routes: '/mobile/manage'
      views: never
    }
    'src/pages/mobile/profile.vue': {
      routes: '/mobile/profile'
      views: never
    }
    'src/pages/mobile/reports.vue': {
      routes: '/mobile/reports'
      views: never
    }
    'src/pages/mobile/wallets.vue': {
      routes: '/mobile/wallets'
      views: never
    }
    'src/pages/register.vue': {
      routes: '/register'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
